services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopper-backend
    depends_on:
      - mongo
    command: npm run dev
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=development
      - PORT=3030
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo_data:
