version: "3.8"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=development
      - PORT=3030
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
